Update Nussinov.jl
ERROR: MethodError: no method matching get_kernel(::SubString{String})
:::
function get_kernel(name::String)
    # ...
end

# To:
function get_kernel(name::AbstractString)  # Accepts both String and SubString
    # ...
end
:::
The get_kernel function expects String but receives SubString{String} from command-line parsing.

# Nussinov recurrence: S[i,j] = max(S[i+1,j], S[i,j-1], S[i+1,j-1] + match, ...)
# Dependencies form anti-diagonals

function kernel_nussinov_wavefront!(S, seq)
    n = length(seq)
    
    # Process anti-diagonals (can be parallelized)
    for d in 2:n  # diagonal offset
        # All (i, j) where j - i == d can be computed in parallel
        @threads :static for i in 1:n-d+1
            j = i + d - 1
            @inbounds begin
                S[i,j] = max(S[i+1,j], S[i,j-1])
                if match(seq[i], seq[j])
                    S[i,j] = max(S[i,j], S[i+1,j-1] + 1)
                end
                for k in i+1:j-1
                    S[i,j] = max(S[i,j], S[i,k] + S[k+1,j])
                end
            end
        end
    end
end